server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  output:
    ansi.enabled: always

logging:
  level:
    org.hibernate.SQL: debug
